### ISSUE TITLE
It is possible to give two people the same nick

### ISSUE THREAD

**Issue by Akuli** [ThePhilgrim/MantaTail#61]
Suppose that Alice and Bob connect to MantaTail, and both say `NICK x`. This is not an error:
![m](https://user-images.githubusercontent.com/18505570/149356905-d76a1c2e-2856-4544-9e44-b4ab7312ba16.png)

Then Alice and Bob both send `USER x`. Finally, Alice and Bob both send `JOIN #foo`. Now `#foo` now has two different users on it, both named `x`, one as the founder (`~` prefix) and one as not the founder.

![m2](https://user-images.githubusercontent.com/18505570/149357293-83787615-5bd5-4d5c-8fdf-02eadb24d2de.png)

I didn't explore what happens if a third user joins in and tries to send a message to nickname `x`. This is already bad enough to be considered a bug :)

**Comment by ThePhilgrim** [comment]
@Akuli On Libera, this seems to lead to the server closing the connection with the client that doesn't provide user first.

`ERROR :Closing Link: 127.0.0.1 (Overridden)`

![Skärmavbild 2022-01-13 kl  22 03 20](https://user-images.githubusercontent.com/76887896/149409110-2755ce32-0d05-4fb3-8914-f4c4419d0d7b.png)

I wonder if it would make more sense to block user 2 from providing a nick that somebody else already has, even if they didn't yet provide both "nick" & "user"

**Comment by Akuli** [comment]
I see a few ways to solve this, and I don't have a clear idea of which way is better:
- When the nickname is given, instantiate the user object and set the username to None (if it's not given yet). You don't need the username for most things, so setting it to None should be fine, and duplicate usernames aren't a problem anyway.
- Check if the nick is taken not only when the `NICK` command is received, but also when the user object has just been instantiated. This is potentially not as clean, because you need to check the nick in two places. If I understood correctly, this is what libera seems to be doing.
