### ISSUE TITLE
Names list (353) does not include founder mode

### ISSUE THREAD

**Issue by Akuli** [ThePhilgrim/MantaTail#62]
On libera, if my nickname is `asdf2` and I join a channel that doesn't exist, the names list includes me:

```
JOIN #akuli-testing
:asdf2!~asdf2@82-203-163-9.bb.dnainternet.fi JOIN #akuli-testing
:strontium.libera.chat MODE #akuli-testing +Cnst
:strontium.libera.chat 353 asdf2 @ #akuli-testing :@asdf2
:strontium.libera.chat 366 asdf2 #akuli-testing :End of /NAMES list.
```

Ignoring the noise, `:@asdf2` is the list of users on this channel, and I am an operator because I have `@` in front of my nickname. The `@` character is also repeated just before the channel name.

With mantatail, I get:

```
JOIN #akuli-testing
:asdf2!asdf2@127.0.0.1 JOIN #akuli-testing
:mantatail 353 asdf2 = #akuli-testing :asdf2 
:mantatail 366 asdf2 #akuli-testing :End of /NAMES list.
```

Note that there is `=`, which presumably means I am nothing special: not a founder, not an operator, not anything else. I also don't have anything prefixed in front of my name. But if another user (named `x`) joins, their names list indicates that I am the founder, because I then get to have `~` in front of my name:

```
:mantatail 353 x = #akuli-testing :x ~asdf2
```

**Comment by ThePhilgrim** [comment]
@Akuli 
Thank you for submitting this issue. As seen in the screenshot below, the `@` character before the channel name has nothing to do with you as a user, but with the channel mode. 

`=` represents a public channel and `@` represents a secret channel. It is true that Mantatail currently only supports public channels.

![Skärmavbild 2022-01-18 kl  22 05 47](https://user-images.githubusercontent.com/76887896/150018745-50673daf-8c2f-47ac-a81e-c59475639737.png)


However, with the correct behavior of Mantatail, you would see the user prefix in front of your own name when you join a channel. I will make sure this is fixed.

**Comment by Akuli** [comment]
Indeed, I was just guessing what the meaning of `=` might be :)
